const { body, validationResult, oneOf } = require('express-validator');

// Account creation validation
// Note: player_tag is AUTO-GENERATED by server, not provided by client
const validateAccountCreation = [
  body('display_name')
    .isLength({ min: 2, max: 20 })
    .withMessage('Display name must be 2-20 characters')
    .matches(/^[a-zA-Z0-9_ ]+$/)
    .withMessage('Display name can only contain letters, numbers, spaces, and underscores'),
  
  body('email')
    .isEmail()
    .normalizeEmail()
    .withMessage('Valid email address required'),
  
  body('password')
    .isLength({ min: 6 })
    .withMessage('Password must be at least 6 characters'),
  
  (req, res, next) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        status: 'error',
        message: 'Validation failed',
        errors: errors.array()
      });
    }
    next();
  }
];

// Login validation - supports email OR (display_name + player_tag)
const validateLogin = [
  body('password')
    .notEmpty()
    .withMessage('Password is required'),
  
  oneOf(
    [
      // Option 1: Email login
      [
        body('email')
          .isEmail()
          .normalizeEmail()
          .withMessage('Valid email address required'),
      ],
      // Option 2: Tag login (display_name + player_tag)
      [
        body('display_name')
          .notEmpty()
          .withMessage('Display name is required'),
        body('player_tag')
          .notEmpty()
          .withMessage('Player tag is required'),
      ],
    ],
    'Must provide either email OR (display_name + player_tag)'
  ),
  
  (req, res, next) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        status: 'error',
        message: 'Validation failed',
        errors: errors.array()
      });
    }
    next();
  }
];

module.exports = {
  validateAccountCreation,
  validateLogin
};